# Generated by Django 5.2.17 on 2026-08-10 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0002_pricepage_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headings', to='pricelist.pricepage')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
