# Generated by Django 5.2.17 on 2026-08-11 10:44

from django.db import migrations


def backfill_user_profiles(apps, schema_editor):
    UserProfile = apps.get_model("usermanage", "UserProfile")
    User = apps.get_model("auth", "User")
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(backfill_user_profiles, migrations.RunPython.noop),
    ]
