# Generated by Django 5.0.7 on 2026-07-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('LOW', 'LOW'), ('NIL', 'NIL')], default='OK', max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
    ]
