# Generated by Django 5.0.7 on 2026-07-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_time', models.DateTimeField(auto_now_add=True)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('products_updated', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-sync_time'],
            },
        ),
    ]
