# Generated by Django 5.0.7 on 2026-07-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_synchistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchistory',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
