# Generated by Django 5.0.7 on 2026-07-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_synchistory_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synchistory',
            name='active',
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
