# Generated by Django 5.0.7 on 2026-07-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_synchistory_active_product_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
