# Generated by Django 5.0.7 on 2026-07-30 06:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_syncsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='synchistory',
            old_name='products_updated',
            new_name='added_count',
        ),
        migrations.RemoveField(
            model_name='synchistory',
            name='file_hash',
        ),
        migrations.RemoveField(
            model_name='synchistory',
            name='success',
        ),
        migrations.AddField(
            model_name='synchistory',
            name='removed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synchistory',
            name='restored_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synchistory',
            name='status',
            field=models.CharField(default='SUCCESS', max_length=20),
        ),
        migrations.AddField(
            model_name='synchistory',
            name='updated_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='synchistory',
            name='sync_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
