# Generated by Django 5.0.7 on 2026-07-30 06:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_products_updated_synchistory_added_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SyncSetting',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'subcategory', 'level3', 'level4', 'product_name']},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='hierarchy_path',
            field=models.CharField(blank=True, db_index=True, default='', max_length=600),
        ),
        migrations.AddField(
            model_name='product',
            name='level3',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='level4',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='avg_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(db_index=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('LOW', 'LOW'), ('NIL', 'NIL')], db_index=True, default='OK', max_length=10),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_name'], name='inventory_p_product_3437c4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='inventory_p_categor_b457a1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['subcategory'], name='inventory_p_subcate_463b26_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['level3'], name='inventory_p_level3_796085_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['level4'], name='inventory_p_level4_47fdea_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['hierarchy_path'], name='inventory_p_hierarc_59d12f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active'], name='inventory_p_active_ee46da_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='inventory_p_status_2ba142_idx'),
        ),
    ]
