# Generated by Django 5.0.7 on 2026-07-30 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_delete_syncsetting_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='synchistory',
            options={'ordering': ['-started_at']},
        ),
        migrations.RemoveField(
            model_name='synchistory',
            name='added_count',
        ),
        migrations.RemoveField(
            model_name='synchistory',
            name='removed_count',
        ),
        migrations.RemoveField(
            model_name='synchistory',
            name='restored_count',
        ),
        migrations.RemoveField(
            model_name='synchistory',
            name='sync_time',
        ),
        migrations.RemoveField(
            model_name='synchistory',
            name='updated_count',
        ),
        migrations.AddField(
            model_name='synchistory',
            name='added',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synchistory',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synchistory',
            name='duration_seconds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='synchistory',
            name='removed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synchistory',
            name='restored',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synchistory',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='synchistory',
            name='total_products',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synchistory',
            name='updated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='synchistory',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='SUCCESS', max_length=10),
        ),
    ]
