# Generated by Django 5.0.7 on 2026-07-30 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_synchistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='synchistory',
            options={'ordering': ['-sync_time']},
        ),
        migrations.RenameField(
            model_name='synchistory',
            old_name='added',
            new_name='added_count',
        ),
        migrations.RenameField(
            model_name='synchistory',
            old_name='removed',
            new_name='removed_count',
        ),
        migrations.RenameField(
            model_name='synchistory',
            old_name='restored',
            new_name='restored_count',
        ),
        migrations.RenameField(
            model_name='synchistory',
            old_name='updated',
            new_name='updated_count',
        ),
        migrations.RemoveField(
            model_name='synchistory',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='synchistory',
            name='started_at',
        ),
        migrations.AddField(
            model_name='synchistory',
            name='sync_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='synchistory',
            name='duration_seconds',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Time taken to complete the sync.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='synchistory',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, default='SUCCESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='synchistory',
            name='total_products',
            field=models.PositiveIntegerField(default=0, help_text='Total active products after this sync.'),
        ),
    ]
