# Generated by Django 5.0.7 on 2026-07-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_synchistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synchistory',
            name='duration_seconds',
        ),
        migrations.AlterField(
            model_name='synchistory',
            name='total_products',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
