# Generated by Django 5.0.7 on 2026-07-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_synchistory_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchistory',
            name='duration_seconds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
