# Generated by Django 5.0.7 on 2026-07-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_synchistory_duration_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_hash', models.CharField(blank=True, default='', max_length=64)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('added', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('removed', models.PositiveIntegerField(default=0)),
                ('restored', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
