# Generated by Django 5.2.17 on 2026-08-08 10:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_syncsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
