# Generated by Django 5.2.17 on 2026-08-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_rename_avg_cost_product_cost_remove_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncsetting',
            name='customer_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
