# Generated by Django 5.2.17 on 2026-08-09 14:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('total_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='customers.customer')),
            ],
            options={
                'ordering': ['-date', 'invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, default='', max_length=600)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('sales_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customers.invoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
