# Generated by Django 5.2.17 on 2026-08-10 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['date', 'invoice_number']},
        ),
    ]
